### ISSUE TITLE
Queue for !s

### ISSUE THREAD

**Issue by tinlun123** [professional-programmingers/GeBeO#27]
Due to larger amounts of !s usage, we should implement a queue system for !s, first come first serve. There should be a command to !sclear queue and to !sskip. !sstop could be used to clear, but !sclear should be an alias too.

**Comment by heartles** [comment]
Alternative idea from discord:  
Have a bank of "speaker" bots that only exist to play sounds  
These bots could either be hidden from the sidebar by excluding them from channels or by having them be offline when not playing a sound

**Comment by heartles** [comment]
#28
