### ISSUE TITLE
Speaker bots to complement !s

### ISSUE THREAD

**Issue by tinlun123** [professional-programmingers/GeBeO#28]
Currently the bot's !s command gets overloaded if there are too many requests for !s. What if there are a few (4?) speaker bots that is controlled by GeBeO to play sounds according to requests. That way we can have 5 !s requests going on at once.

The speaker bots won't be automatically invited by GeBeO but there will be a command that prints out all of the correct invite links. 

There's the issue of the bots polluting the user list. 2 possible solutions: 
- The bots will stay offline until it is needed then GeBeO will start them up and run them. Possible problem is that the bots will take too long to startup (GeBeO takes really long to startup).
- The bots will have their own roles, and that role will make the bots not show up in text channels. Possible problem is if we somehow aren't able to automate adding roles to channels then it'll be really laborious to configure each channel to hide the bots.

**Comment by heartles** [comment]
I just realized we don't necessarily have to have the bots offline, we just need them to display offline.

http://discordpy.readthedocs.io/en/rewrite/api.html?highlight=invisible#discord.Client.change_presence  
http://discordpy.readthedocs.io/en/rewrite/api.html?highlight=invisible#discord.Status

**Comment by tinlun123** [comment]
genius!
