### ISSUE TITLE
Volume for !s and !yt

### ISSUE THREAD

**Issue by heartles** [professional-programmingers/GeBeO#31]
How should we specify it though, should it be a separate command "!vol" or should it be the original command?

`!yt <url> 20`

**Comment by heartles** [comment]
Note that the example syntax for it being part of the original command would be hard to implement if we implemented #25 the way Tin describes

**Comment by notdisliked** [comment]
Is this even really necessary?  the users can control the volume themselves, why should we set it at the code level?

**Comment by heartles** [comment]
That's a good point, hmm.

My thought was when I was trying to play a fairly loud song for you guys the other day and it went blasting into your guys ears but hmm....

**Comment by heartles** [comment]
I think i agree with you that this shouldn't be necessary

**Comment by heartles** [comment]
Closing, we can reopen if it becomes necessary at some point
