### ISSUE TITLE
Bot nickname reset issue

### ISSUE THREAD

**Issue by notdisliked** [professional-programmingers/GeBeO#4]
When running two nickname change commands in quick succession, the bot doesn't set its nickname back to what it was originally.

**Comment by heartles** [comment]
Race condition!! woot woot

**Comment by heartles** [comment]
Okay so the commit I pushed *should* fix it, but my bot is rate limited too much for me to test it. I'm gonna leave this issue open for now.

**Comment by notdisliked** [comment]
I'm gonna go ahead and close it because I can't break it anymore, if it ever happens again we can reopen this.
