### ISSUE TITLE
After christmas is over, turn christmas countdown into something with rich presence

### ISSUE THREAD

**Issue by tinlun123** [professional-programmingers/GeBeO#61]
Rich presence: https://discordapp.com/rich-presence
https://www.reddit.com/r/discordapp/comments/7fu2v5/i_made_spotify_rich_presence_i_think_its_nice/

Some ideas:
- "We could do a daily Markov chain
Start with a big pull of message history, cache it
Save the most recent message at the time
Next day get the messages from that one to the new most recent
We could have a scoring mechanism so we don't end up with shitty ones"

- Daily haiku?

List out some ideas in this issues.

**Comment by heartles** [comment]
We did this!

**Comment by heartles** [comment]
Current implementation is a "X% through <current year>"
