### ISSUE TITLE
Control GeBeO through league chat.

### ISSUE THREAD

**Issue by tinlun123** [professional-programmingers/GeBeO#87]
Would be very interesting if GeBeO can be controlled through league chat (e.g. to add music). That way people can be inside a game and still queue up music. Someone can, for example, pm GeBeO a command to a dedicated league chat-bot and GeBeO can process that somehow.

Some leads: 
https://github.com/TheHolyWaffle/League-of-Legends-XMPP-Chat-Library
https://github.com/RedbackThomson/LoLAlerter

**Comment by jmalexan** [comment]
Looked into this myself, probably never gonna happen.  Riot is very against it and I'd rather not test them.  Gonna close this until something changes.
