### ISSUE TITLE
Implement !spank

### ISSUE THREAD

**Issue by heartles** [professional-programmingers/GeBeO#90]
`!spank @user1 @user2` would produce an image like this one:
![image](https://user-images.githubusercontent.com/9450911/39033334-5e8157d8-4426-11e8-8eed-eb5019dffd1b.png)

**Comment by heartles** [comment]
![image](https://user-images.githubusercontent.com/9450911/39033412-ba5b9da2-4426-11e8-8c56-a2de3be569ff.png)
Base image for reference

**Comment by tinlun123** [comment]
Done
